services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: bun_Dockerfile
    ports:
      # Prod
      - '3000:3000'
      # Dev
      - '5173:5173'
    depends_on:
      - db
    environment:
      - HOST=0.0.0.0
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/local
    volumes:
      - .:/app
      - web_data:/app/node_modules
      - /mnt/AppStorage:/mnt/AppStorage
    # Dev
    command: ['bun', 'run', 'dev', '--host']
    # Prod
    # command: ['bun', './build/index.js']

  db:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: local
    volumes:
      - postgres_data:/var/lib/postgresql/data

  db_admin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    # Stops log spamming from pgadmin4
    attach: false
    depends_on:
      - db

  drizzle_studio:
    container_name: drizzle_studio
    build:
      context: .
      dockerfile: bun_Dockerfile
    ports:
      - '4983:4983'
    depends_on:
      - db
    environment:
      - HOST=0.0.0.0
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/local
      - PORT=4983
    volumes:
      - .:/app
      - web_data:/app/node_modules
    command: ['bun', 'x', 'drizzle-kit', 'studio', '--host', '0.0.0.0', '--port', '4983']

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - '443:443'
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # Ensure this is a file mount
      - /home/zhren/SSL-storage:/etc/nginx/ssl
    depends_on:
      - web

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local
  web_data:
    driver: local
